import puppeteer from "puppeteer-core";
import fs from "fs";
const OUT = process.argv[2];
fs.mkdirSync(OUT, { recursive: true });
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const b = await puppeteer.launch({ executablePath: "/usr/bin/google-chrome", headless: "new", args: ["--no-sandbox", "--use-gl=swiftshader", "--enable-unsafe-swiftshader", "--hide-scrollbars"] });
const p = await b.newPage();
p.on("pageerror", (e) => console.log("PAGEERROR:", String(e).slice(0, 150)));
await p.setViewport({ width: 768, height: 1024 });
await p.goto("http://localhost:4173/", { waitUntil: "load", timeout: 60000 });
await sleep(4000);
await p.screenshot({ path: `${OUT}/t01-hero.png` });
await p.evaluate(() => { const el = document.querySelector("#identity"); window.scrollTo({ top: el.getBoundingClientRect().top + window.scrollY + innerHeight * 0.6, behavior: "instant" }); });
await sleep(2500);
await p.screenshot({ path: `${OUT}/t02-identity.png` });
await p.evaluate(() => { const el = document.querySelector("#events"); window.scrollTo({ top: el.getBoundingClientRect().top + window.scrollY - 40, behavior: "instant" }); });
await sleep(2200);
await p.screenshot({ path: `${OUT}/t03-events.png` });
const overflow = await p.evaluate(() => document.documentElement.scrollWidth);
console.log("scrollWidth @768:", overflow);
await b.close();
